var CONFIG = {
  engineTypes: {
    1: {name: 'Search Engine', default: true},
    2: {name: 'Video', default: true},
    3: {name: 'Dictionary', default: true},
    4: {name: 'EBook', default: true},
    5: {name: 'Search Engine'},
    6: {name: 'Video'},
    7: {name: 'Dictionary'},
    8: {name: 'EBook'},
    9: {name: 'Sub', default: true},
    10: {name: 'Torrents', default: true},
  },
  engines: {
    // Search engines
    google: {
      order: 1,
      typeId: 5,
      defaultTypeId: 1,
      displayName: 'Google',
      open: true,
      // view-source:https://www.google.com/supported_domains
      hosts: [
      'ipv4.google.com',
      'ipv6.google.com',
      'ipv6.google.com.hk',
      'www.google.com',
      'www.google.ad',
      'www.google.ae',
      'www.google.com.af',
      'www.google.com.ag',
      'www.google.com.ai',
      'www.google.al',
      'www.google.am',
      'www.google.co.ao',
      'www.google.com.ar',
      'www.google.as',
      'www.google.at',
      'www.google.com.au',
      'www.google.az',
      'www.google.ba',
      'www.google.com.bd',
      'www.google.be',
      'www.google.bf',
      'www.google.bg',
      'www.google.com.bh',
      'www.google.bi',
      'www.google.bj',
      'www.google.com.bn',
      'www.google.com.bo',
      'www.google.com.br',
      'www.google.bs',
      'www.google.bt',
      'www.google.co.bw',
      'www.google.by',
      'www.google.com.bz',
      'www.google.ca',
      'www.google.cd',
      'www.google.cf',
      'www.google.cg',
      'www.google.ch',
      'www.google.ci',
      'www.google.co.ck',
      'www.google.cl',
      'www.google.cm',
      'www.google.cn',
      'www.google.com.co',
      'www.google.co.cr',
      'www.google.com.cu',
      'www.google.cv',
      'www.google.com.cy',
      'www.google.cz',
      'www.google.de',
      'www.google.dj',
      'www.google.dk',
      'www.google.dm',
      'www.google.com.do',
      'www.google.dz',
      'www.google.com.ec',
      'www.google.ee',
      'www.google.com.eg',
      'www.google.es',
      'www.google.com.et',
      'www.google.fi',
      'www.google.com.fj',
      'www.google.fm',
      'www.google.fr',
      'www.google.ga',
      'www.google.ge',
      'www.google.gg',
      'www.google.com.gh',
      'www.google.com.gi',
      'www.google.gl',
      'www.google.gm',
      'www.google.gp',
      'www.google.gr',
      'www.google.com.gt',
      'www.google.gy',
      'www.google.com.hk',
      'www.google.hn',
      'www.google.hr',
      'www.google.ht',
      'www.google.hu',
      'www.google.co.id',
      'www.google.ie',
      'www.google.co.il',
      'www.google.im',
      'www.google.co.in',
      'www.google.iq',
      'www.google.is',
      'www.google.it',
      'www.google.je',
      'www.google.com.jm',
      'www.google.jo',
      'www.google.co.jp',
      'www.google.co.ke',
      'www.google.com.kh',
      'www.google.ki',
      'www.google.kg',
      'www.google.co.kr',
      'www.google.com.kw',
      'www.google.kz',
      'www.google.la',
      'www.google.com.lb',
      'www.google.li',
      'www.google.lk',
      'www.google.co.ls',
      'www.google.lt',
      'www.google.lu',
      'www.google.lv',
      'www.google.com.ly',
      'www.google.co.ma',
      'www.google.md',
      'www.google.me',
      'www.google.mg',
      'www.google.mk',
      'www.google.ml',
      'www.google.com.mm',
      'www.google.mn',
      'www.google.ms',
      'www.google.com.mt',
      'www.google.mu',
      'www.google.mv',
      'www.google.mw',
      'www.google.com.mx',
      'www.google.com.my',
      'www.google.co.mz',
      'www.google.com.na',
      'www.google.com.nf',
      'www.google.com.ng',
      'www.google.com.ni',
      'www.google.ne',
      'www.google.nl',
      'www.google.no',
      'www.google.com.np',
      'www.google.nr',
      'www.google.nu',
      'www.google.co.nz',
      'www.google.com.om',
      'www.google.com.pa',
      'www.google.com.pe',
      'www.google.com.pg',
      'www.google.com.ph',
      'www.google.com.pk',
      'www.google.pl',
      'www.google.pn',
      'www.google.com.pr',
      'www.google.ps',
      'www.google.pt',
      'www.google.com.py',
      'www.google.com.qa',
      'www.google.ro',
      'www.google.ru',
      'www.google.rw',
      'www.google.com.sa',
      'www.google.com.sb',
      'www.google.sc',
      'www.google.se',
      'www.google.com.sg',
      'www.google.sh',
      'www.google.si',
      'www.google.sk',
      'www.google.com.sl',
      'www.google.sn',
      'www.google.so',
      'www.google.sm',
      'www.google.sr',
      'www.google.st',
      'www.google.com.sv',
      'www.google.td',
      'www.google.tg',
      'www.google.co.th',
      'www.google.com.tj',
      'www.google.tk',
      'www.google.tl',
      'www.google.tm',
      'www.google.tn',
      'www.google.to',
      'www.google.com.tr',
      'www.google.tt',
      'www.google.com.tw',
      'www.google.co.tz',
      'www.google.com.ua',
      'www.google.co.ug',
      'www.google.co.uk',
      'www.google.com.uy',
      'www.google.co.uz',
      'www.google.com.vc',
      'www.google.co.ve',
      'www.google.vg',
      'www.google.co.vi',
      'www.google.com.vn',
      'www.google.vu',
      'www.google.ws',
      'www.google.rs',
      'www.google.co.za',
      'www.google.co.zm',
      'www.google.co.zw',
      'www.google.cat'
    ],
      url: 'https://www.google.com.hk/search?q=%s'
    },
    aol: {
      order: 4,
      typeId: 5,
      defaultTypeId: 1,
      displayName: 'Aol Search',
      open: false,
      hosts: ['www.aolsearch.com', 'search.aol.com'],
      url: 'http://www.aolsearch.com/search?q=%s'
    },
    baidu: {
      order: 2,
      typeId: 5,
      defaultTypeId: 1,
      displayName: 'Baidu',
      open: true,
      hosts: ['www.baidu.com'],
      url: 'https://www.baidu.com/s?wd=%s'
    },
    bing: {
      order: 3,
      typeId: 5,
      defaultTypeId: 1,
      displayName: 'Bing',
      open: true,
      hosts: [
        'www.bing.com', 'bing.co', 'bing.co.uk', 'bing.com', 'be.bing.com', 'br.bing.com', 'ca.bing.com', 'cn.bing.com', 'de.bing.com', 'fr.bing.com', 'hk.bing.com', 'it.bing.com', 'jp.bing.com', 'm.bing.com', 'nz.bing.com', 'ssl.bing.com', 'uk.bing.com'
      ],
      url: 'https://cn.bing.com/search?q=%s'
    },
    yahoo: {
      order: 5,
      typeId: 5,
      defaultTypeId: 1,
      displayName: 'Yahoo',
      open: false,
      hosts: [
        'at.search.yahoo.com', 'au.search.yahoo.com', 'br.search.yahoo.com', 'ca.search.yahoo.com', 'qc.search.yahoo.com', 'ch.search.yahoo.com', 'chfr.search.yahoo.com', 'chit.search.yahoo.com', 'cl.search.yahoo.com', 'cn.search.yahoo.com', 'yahoo.cn', 'co.search.yahoo.com', 'espanol.search.yahoo.com', 'search.yahoo.com', 'de.search.yahoo.com', 'dk.search.yahoo.com', 'es.search.yahoo.com', 'fi.search.yahoo.com', 'fr.search.yahoo.com', 'gr.search.yahoo.com', 'hk.search.yahoo.com', 'id.search.yahoo.com', 'in.search.yahoo.com', 'it.search.yahoo.com', 'maktoob.search.yahoo.com', 'search.yahoo.co.jp', 'kr.search.yahoo.com', 'mx.search.yahoo.com', 'malaysia.search.yahoo.com', 'nl.search.yahoo.com', 'no.search.yahoo.com', 'nz.search.yahoo.com', 'pe.search.yahoo.com', 'ph.search.yahoo.com', 'pl.search.yahoo.com', 'ru.search.yahoo.com', 'se.search.yahoo.com', 'sg.search.yahoo.com', 'th.search.yahoo.com', 'tr.search.yahoo.com', 'tw.search.yahoo.com', 'uk.search.yahoo.com', 've.search.yahoo.com', 'vn.search.yahoo.com'
      ],
      url: 'https://search.yahoo.com/search?p=%s'
    },
    sogou: {
      order: 6,
      typeId: 5,
      defaultTypeId: 1,
      displayName: 'Sogou',
      open: false,
      hosts: ['www.sogou.com'],
      url: 'https://www.sogou.com/web?query=%s'
    },
    360: {
      order: 7,
      typeId: 5,
      defaultTypeId: 1,
      displayName: '360',
      open: false,
      hosts: ['www.so.com'],
      url: 'https://www.so.com/s?q=%s'
    },
    duck: {
      order: 8,
      typeId: 5,
      defaultTypeId: 1,
      displayName: 'DuckDuckGo',
      open: true,
      hosts: ['duckduckgo.com'],
      url: 'https://duckduckgo.com/?q=%s'
    },
    // Movie, Video, Sub
    doubanMovie: {
      order: 9,
      typeId: 6,
      defaultTypeId: 2,
      displayName: 'douban movie',
      open: true,
      hosts: ['movie.douban.com'],
      url: 'https://movie.douban.com/subject_search?search_text=%s'
    },
    RARBG: {
      order: 10,
      typeId: 6,
      defaultTypeId: 10,
      displayName: 'RARBG',
      open: true,
      hosts: ['rarbg.to'],
      url: 'https://rarbg.to/torrents.php?search=%s'
    },
    AcFun: {
      order: 11,
      typeId: 6,
      defaultTypeId: 2,
      displayName: 'AcFun',
      open: false,
      hosts: ['www.acfun.tv'],
      url: 'http://www.acfun.tv/search/#query=%s'
    },
    bilibili: {
      order: 12,
      typeId: 6,
      defaultTypeId: 2,
      displayName: 'bilibili',
      open: true,
      hosts: ['search.bilibili.com'],
      url: 'http://search.bilibili.com/all?keyword=%s'
    },
    tencentVideo: {
      order: 13,
      typeId: 6,
      defaultTypeId: 2,
      displayName: 'Tencent Video',
      open: true,
      hosts: ['v.qq.com'],
      url: 'http://v.qq.com/x/search/?q=%s'
    },
    youtube: {
      order: 14,
      typeId: 6,
      defaultTypeId: 2,
      displayName: 'YouTube',
      open: true,
      hosts: ['www.youtube.com'],
      url: 'https://www.youtube.com/results?search_query=%s'
    },
    subHD: {
      order: 15,
      typeId: 6,
      defaultTypeId: 9,
      displayName: 'Sub HD',
      open: true,
      hosts: ['subhd.com'],
      url: 'http://subhd.com/search/%s'
    },
    zimuku: {
      order: 16,
      typeId: 6,
      defaultTypeId: 9,
      displayName: 'zimuku',
      open: false,
      hosts: ['www.zimuku.net'],
      url: 'http://www.zimuku.net/search?q=%s'
    },
    // Dictionary
    iciba: {
      order: 17,
      typeId: 7,
      defaultTypeId: 3,
      displayName: 'iciba',
      open: true,
      hosts: ['www.iciba.com'],
      url: 'http://www.iciba.com/%s'
    },
    zdic: {
      order: 17,
      typeId: 7,
      defaultTypeId: 3,
      displayName: '汉典',
      open: true,
      hosts: ['www.zdic.net'],
      url: 'http://www.zdic.net/search/?c=3&q=%s'
    },
    // EBook
    readFree: {
      order: 18,
      typeId: 8,
      defaultTypeId: 4,
      displayName: 'readFree',
      open: true,
      hosts: ['readfree.me'],
      url: 'http://readfree.me/search/?q=%s'
    },
    ITeBooks: {
      order: 19,
      typeId: 8,
      defaultTypeId: 4,
      displayName: 'IT eBooks',
      open: true,
      hosts: ['it-ebooks.info'],
      url: 'https://cse.google.com/cse?cx=013493258683483688568:xhfa6ctm1ki&q=%s#gsc.tab=0&gsc.q=%s'
    }
  },
  devMode: true
};